name: test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [ 17 ]
        os: [ubuntu, windows]
    steps:
      - name: Check out repo
        uses: actions/checkout@v3.3.0
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          check-latest: true
          cache: 'gradle'
      - name: Run Gradle's test task
        run: ./gradlew --no-daemon --parallel --continue --build-cache --stacktrace test
